version: 2

project_name: packer-plugin-verda

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go test ./...
    - make plugin-check

builds:
  - id: packer-plugin-verda
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - >-
        -s -w
        -X {{ .ModulePath }}/version.Version={{ .Version }}
        -X {{ .ModulePath }}/version.VersionPrerelease=
        -X {{ .ModulePath }}/version.VersionMetadata=
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"

archives:
  - id: packer-plugin-verda
    formats:
      - zip
    files:
      - none*
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  use: github-native
