// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package instance

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	ClientID                   *string      `mapstructure:"client_id" cty:"client_id" hcl:"client_id"`
	ClientSecret               *string      `mapstructure:"client_secret" cty:"client_secret" hcl:"client_secret"`
	BaseURL                    *string      `mapstructure:"base_url" cty:"base_url" hcl:"base_url"`
	Debug                      *bool        `mapstructure:"debug" cty:"debug" hcl:"debug"`
	InstanceType               *string      `mapstructure:"instance_type" cty:"instance_type" hcl:"instance_type"`
	Image                      *string      `mapstructure:"image" cty:"image" hcl:"image"`
	Hostname                   *string      `mapstructure:"hostname" cty:"hostname" hcl:"hostname"`
	Description                *string      `mapstructure:"description" cty:"description" hcl:"description"`
	LocationCode               *string      `mapstructure:"location_code" cty:"location_code" hcl:"location_code"`
	Contract                   *string      `mapstructure:"contract" cty:"contract" hcl:"contract"`
	Pricing                    *string      `mapstructure:"pricing" cty:"pricing" hcl:"pricing"`
	IsSpot                     *bool        `mapstructure:"is_spot" cty:"is_spot" hcl:"is_spot"`
	Coupon                     *string      `mapstructure:"coupon" cty:"coupon" hcl:"coupon"`
	SSHKeyIDs                  []string     `mapstructure:"ssh_key_ids" cty:"ssh_key_ids" hcl:"ssh_key_ids"`
	TemporarySSHKeyName        *string      `mapstructure:"temporary_ssh_key_name" cty:"temporary_ssh_key_name" hcl:"temporary_ssh_key_name"`
	SkipTemporarySSHKey        *bool        `mapstructure:"skip_temporary_ssh_key" cty:"skip_temporary_ssh_key" hcl:"skip_temporary_ssh_key"`
	StartupScriptID            *string      `mapstructure:"startup_script_id" cty:"startup_script_id" hcl:"startup_script_id"`
	StartupScript              *string      `mapstructure:"startup_script" cty:"startup_script" hcl:"startup_script"`
	StartupScriptName          *string      `mapstructure:"startup_script_name" cty:"startup_script_name" hcl:"startup_script_name"`
	DeleteStartupScript        *bool        `mapstructure:"delete_startup_script" cty:"delete_startup_script" hcl:"delete_startup_script"`
	ExistingVolumeIDs          []string     `mapstructure:"existing_volume_ids" cty:"existing_volume_ids" hcl:"existing_volume_ids"`
	OSVolumeName               *string      `mapstructure:"os_volume_name" cty:"os_volume_name" hcl:"os_volume_name"`
	OSVolumeSize               *int         `mapstructure:"os_volume_size" cty:"os_volume_size" hcl:"os_volume_size"`
	OSVolumeSpotBehavior       *string      `mapstructure:"os_volume_spot_behavior" cty:"os_volume_spot_behavior" hcl:"os_volume_spot_behavior"`
	Volumes                    []FlatVolume `mapstructure:"volume" cty:"volume" hcl:"volume"`
	ArtifactType               *string      `mapstructure:"artifact_type" cty:"artifact_type" hcl:"artifact_type"`
	CloneOSVolume              *bool        `mapstructure:"clone_os_volume" cty:"clone_os_volume" hcl:"clone_os_volume"`
	ArtifactVolumeName         *string      `mapstructure:"artifact_volume_name" cty:"artifact_volume_name" hcl:"artifact_volume_name"`
	ArtifactVolumeLocationCode *string      `mapstructure:"artifact_volume_location_code" cty:"artifact_volume_location_code" hcl:"artifact_volume_location_code"`
	SkipShutdownBeforeArtifact *bool        `mapstructure:"skip_shutdown_before_artifact" cty:"skip_shutdown_before_artifact" hcl:"skip_shutdown_before_artifact"`
	KeepInstance               *bool        `mapstructure:"keep_instance" cty:"keep_instance" hcl:"keep_instance"`
	DeletePermanently          *bool        `mapstructure:"delete_permanently" cty:"delete_permanently" hcl:"delete_permanently"`
	VolumeIDsToDelete          []string     `mapstructure:"volume_ids_to_delete" cty:"volume_ids_to_delete" hcl:"volume_ids_to_delete"`
	PollInterval               *string      `mapstructure:"poll_interval" cty:"poll_interval" hcl:"poll_interval"`
	InstanceTimeout            *string      `mapstructure:"instance_timeout" cty:"instance_timeout" hcl:"instance_timeout"`
	APITimeout                 *string      `mapstructure:"api_timeout" cty:"api_timeout" hcl:"api_timeout"`
	AllowedSSHStatuses         []string     `mapstructure:"allowed_ssh_statuses" cty:"allowed_ssh_statuses" hcl:"allowed_ssh_statuses"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"client_id":                     &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"client_secret":                 &hcldec.AttrSpec{Name: "client_secret", Type: cty.String, Required: false},
		"base_url":                      &hcldec.AttrSpec{Name: "base_url", Type: cty.String, Required: false},
		"debug":                         &hcldec.AttrSpec{Name: "debug", Type: cty.Bool, Required: false},
		"instance_type":                 &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"image":                         &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"hostname":                      &hcldec.AttrSpec{Name: "hostname", Type: cty.String, Required: false},
		"description":                   &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"location_code":                 &hcldec.AttrSpec{Name: "location_code", Type: cty.String, Required: false},
		"contract":                      &hcldec.AttrSpec{Name: "contract", Type: cty.String, Required: false},
		"pricing":                       &hcldec.AttrSpec{Name: "pricing", Type: cty.String, Required: false},
		"is_spot":                       &hcldec.AttrSpec{Name: "is_spot", Type: cty.Bool, Required: false},
		"coupon":                        &hcldec.AttrSpec{Name: "coupon", Type: cty.String, Required: false},
		"ssh_key_ids":                   &hcldec.AttrSpec{Name: "ssh_key_ids", Type: cty.List(cty.String), Required: false},
		"temporary_ssh_key_name":        &hcldec.AttrSpec{Name: "temporary_ssh_key_name", Type: cty.String, Required: false},
		"skip_temporary_ssh_key":        &hcldec.AttrSpec{Name: "skip_temporary_ssh_key", Type: cty.Bool, Required: false},
		"startup_script_id":             &hcldec.AttrSpec{Name: "startup_script_id", Type: cty.String, Required: false},
		"startup_script":                &hcldec.AttrSpec{Name: "startup_script", Type: cty.String, Required: false},
		"startup_script_name":           &hcldec.AttrSpec{Name: "startup_script_name", Type: cty.String, Required: false},
		"delete_startup_script":         &hcldec.AttrSpec{Name: "delete_startup_script", Type: cty.Bool, Required: false},
		"existing_volume_ids":           &hcldec.AttrSpec{Name: "existing_volume_ids", Type: cty.List(cty.String), Required: false},
		"os_volume_name":                &hcldec.AttrSpec{Name: "os_volume_name", Type: cty.String, Required: false},
		"os_volume_size":                &hcldec.AttrSpec{Name: "os_volume_size", Type: cty.Number, Required: false},
		"os_volume_spot_behavior":       &hcldec.AttrSpec{Name: "os_volume_spot_behavior", Type: cty.String, Required: false},
		"volume":                        &hcldec.BlockListSpec{TypeName: "volume", Nested: hcldec.ObjectSpec((*FlatVolume)(nil).HCL2Spec())},
		"artifact_type":                 &hcldec.AttrSpec{Name: "artifact_type", Type: cty.String, Required: false},
		"clone_os_volume":               &hcldec.AttrSpec{Name: "clone_os_volume", Type: cty.Bool, Required: false},
		"artifact_volume_name":          &hcldec.AttrSpec{Name: "artifact_volume_name", Type: cty.String, Required: false},
		"artifact_volume_location_code": &hcldec.AttrSpec{Name: "artifact_volume_location_code", Type: cty.String, Required: false},
		"skip_shutdown_before_artifact": &hcldec.AttrSpec{Name: "skip_shutdown_before_artifact", Type: cty.Bool, Required: false},
		"keep_instance":                 &hcldec.AttrSpec{Name: "keep_instance", Type: cty.Bool, Required: false},
		"delete_permanently":            &hcldec.AttrSpec{Name: "delete_permanently", Type: cty.Bool, Required: false},
		"volume_ids_to_delete":          &hcldec.AttrSpec{Name: "volume_ids_to_delete", Type: cty.List(cty.String), Required: false},
		"poll_interval":                 &hcldec.AttrSpec{Name: "poll_interval", Type: cty.String, Required: false},
		"instance_timeout":              &hcldec.AttrSpec{Name: "instance_timeout", Type: cty.String, Required: false},
		"api_timeout":                   &hcldec.AttrSpec{Name: "api_timeout", Type: cty.String, Required: false},
		"allowed_ssh_statuses":          &hcldec.AttrSpec{Name: "allowed_ssh_statuses", Type: cty.List(cty.String), Required: false},
	}
	return s
}

// FlatVolume is an auto-generated flat version of Volume.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVolume struct {
	Name              *string `mapstructure:"name" cty:"name" hcl:"name"`
	Size              *int    `mapstructure:"size" cty:"size" hcl:"size"`
	Type              *string `mapstructure:"type" cty:"type" hcl:"type"`
	LocationCode      *string `mapstructure:"location_code" cty:"location_code" hcl:"location_code"`
	OnSpotDiscontinue *string `mapstructure:"on_spot_discontinue" cty:"on_spot_discontinue" hcl:"on_spot_discontinue"`
}

// FlatMapstructure returns a new FlatVolume.
// FlatVolume is an auto-generated flat version of Volume.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Volume) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVolume)
}

// HCL2Spec returns the hcl spec of a Volume.
// This spec is used by HCL to read the fields of Volume.
// The decoded values from this spec will then be applied to a FlatVolume.
func (*FlatVolume) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":                &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"size":                &hcldec.AttrSpec{Name: "size", Type: cty.Number, Required: false},
		"type":                &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
		"location_code":       &hcldec.AttrSpec{Name: "location_code", Type: cty.String, Required: false},
		"on_spot_discontinue": &hcldec.AttrSpec{Name: "on_spot_discontinue", Type: cty.String, Required: false},
	}
	return s
}
