name: Acceptance

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  testacc:
    name: Acceptance
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version
          cache: true

      - name: Run acceptance tests
        run: make testacc
        env:
          VERDA_CLIENT_ID: ${{ secrets.VERDA_CLIENT_ID }}
          VERDA_CLIENT_SECRET: ${{ secrets.VERDA_CLIENT_SECRET }}
          VERDA_ACC_INSTANCE_TYPE: ${{ vars.VERDA_ACC_INSTANCE_TYPE }}
          VERDA_ACC_IMAGE: ${{ vars.VERDA_ACC_IMAGE }}
          VERDA_ACC_LOCATION_CODE: ${{ vars.VERDA_ACC_LOCATION_CODE }}
          VERDA_ACC_BASE_URL: ${{ vars.VERDA_ACC_BASE_URL }}
